{- DO NOT EDIT THIS FILE
   THIS FILE IS AUTOMAGICALLY GENERATED AND YOUR CHANGES WILL BE EATEN BY THE GENERATOR OVERLORD

   All changes should go into the Model file (e.g. App/Models/ExampleModel.hs)
-}

module App.Models.Bases.PageType where

import App.Models.Bases.Common
import Data.Maybe
import Data.Time
import Data.Typeable

-- The data type for this model
data Page = Page {
    _id :: String,
    content :: String,
    title :: String
    } deriving (Show, Typeable)

instance DatabaseModel Page where
    tableName _ = "page"

