{- DO NOT EDIT THIS FILE
   THIS FILE IS AUTOMAGICALLY GENERATED AND YOUR CHANGES WILL BE EATEN BY THE GENERATOR OVERLORD

   All changes should go into the Model file (e.g. App/Models/ExampleModel.hs)
-}

module App.Models.Bases.TmpType where

import App.Models.Bases.Common
import Data.Maybe
import Data.Time
import Data.Typeable

-- The data type for this model
data Tmp = Tmp {
    ts :: Maybe UTCTime,
    ts2 :: Maybe ZonedTime
    } deriving (Show, Typeable)

instance DatabaseModel Tmp where
    tableName _ = "tmp"

